// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/17 23:17:27
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/plugins/**/*.{js,ts,mjs}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/composables/**/*.{js,ts,mjs}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/utils/**/*.{js,ts,mjs}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/localCode/solo-code-project/Protein Folding HP Model Energy Landscape/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;